In [ ]:
import numpy as np
climate_data=np.array([[25.0,76.0,99.0],[45.0,68.0,56.0],
                       [12.0,67.0,89.0],[45.0,23.0,78.0],
                       [67.0,34.0,23.0],[78.0,56.0,12.0],
                       [34.0,23.0,45.0],[23.0,45.0,67.0],
                       [56.0,78.0,89.0],[90.0,34.0,23.0],
                       [45.0,67.0,89.0],[23.0,45.0,67.0],
                       [36.0,78.0,90.0],[12.0,34.0,56.0]])
weights=np.array([0.2,0.5,0.3])
average_yeild=np.dot(climate_data,weights)
print("Weighted averages for each region:",average_yeild)



Weighted averages for each region: [72.7 59.8 62.6 43.9 37.3 47.2 31.8 47.2 76.9 41.9 69.2 47.2 73.2 36.2]


In [ ]:
print(climate_data.shape)


(14, 3)


In [5]:
yeild=average_yeild.reshape(14,1)

In [6]:
climate_result=np.concatenate((climate_data,yeild),axis=1)
print("Climate data with weighted averages:\n",climate_result)

Climate data with weighted averages:
 [[25.  76.  99.  72.7]
 [45.  68.  56.  59.8]
 [12.  67.  89.  62.6]
 [45.  23.  78.  43.9]
 [67.  34.  23.  37.3]
 [78.  56.  12.  47.2]
 [34.  23.  45.  31.8]
 [23.  45.  67.  47.2]
 [56.  78.  89.  76.9]
 [90.  34.  23.  41.9]
 [45.  67.  89.  69.2]
 [23.  45.  67.  47.2]
 [36.  78.  90.  73.2]
 [12.  34.  56.  36.2]]
